### ISSUE TITLE
Filenames of aux.c and aux.h are reserved by Windows

### ISSUE THREAD

**Issue by bopoh13** [skeggsb/nouveau#4]
Unable to access files through applications in win7
https://github.com/skeggsb/nouveau/blob/56c2c9a342fe541bb1c72119ad33c1de65a8948d/drm/nouveau/nvkm/subdev/i2c/aux.c#L1-L2
https://github.com/skeggsb/nouveau/blob/aee1c7d1410ae19edf719f221abf78141290b388/drm/nouveau/nvkm/subdev/i2c/aux.h#L1
The same with the file nouveau `nouveau/core/subdev/i2c/aux.c`

**Comment by kubast2** [comment]
@bopoh13 It is due to an old incorrectly replicated feature from OS/2 in NT/DOS. Basically "lpt" "aux" ,imagine that "lpt" "aux" and "com0" (...) "com9" etc. are an alias to /dev/lpt etc. basically you can't access those files because windows is trying to access /dev/aux instead of the file, you need to use OS X or linux or linux VM, using WSL won't help
